services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/frontend
    working_dir: /frontend
    command: npm start  